name: Create PR from Develop to Release

on:
  schedule:
    - cron: '50 11 * * *'  # Runs daily at 6 PM (UTC)
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: master  # Checkout the develop branch

    - name: Create Pull Request
      id: create_pr
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        base: test  # Target branch
        head: master  # Source branch
        title: 'Daily PR from Develop to Release'
        body: 'This PR is automatically created by the GitHub Actions workflow.'
        branch: 'auto-develop-to-release'  # Optional: Branch name for the PR

